# Generated by Django 5.2.11 on 2026-02-05 18:44

import django.core.validators
import django.db.models.deletion
import parking.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("SHORT_TERM", "Short Term (Hourly)"),
                            ("LONG_TERM", "Long Term (Daily/Weekly)"),
                            ("PREMIUM", "Premium/VIP"),
                            ("ECONOMY", "Economy"),
                            ("VALET", "Valet Parking"),
                            ("DISABLED", "Disabled/Accessible"),
                            ("ELECTRIC", "Electric Vehicle"),
                            ("MOTORCYCLE", "Motorcycle"),
                        ],
                        default="SHORT_TERM",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("total_spots", models.PositiveIntegerField(default=100)),
                ("available_spots", models.PositiveIntegerField(default=100)),
                (
                    "terminal",
                    models.CharField(
                        blank=True,
                        help_text="Associated terminal (e.g., Domestic, International)",
                        max_length=50,
                    ),
                ),
                (
                    "floor_level",
                    models.CharField(
                        blank=True,
                        help_text="Floor/Level (e.g., Ground, Level 1)",
                        max_length=20,
                    ),
                ),
                (
                    "distance_to_terminal",
                    models.PositiveIntegerField(
                        default=0, help_text="Walking distance to terminal in meters"
                    ),
                ),
                (
                    "is_covered",
                    models.BooleanField(
                        default=False, help_text="Is the parking area covered?"
                    ),
                ),
                (
                    "has_cctv",
                    models.BooleanField(
                        default=True, help_text="24/7 CCTV surveillance"
                    ),
                ),
                (
                    "has_security",
                    models.BooleanField(default=True, help_text="Security patrol"),
                ),
                (
                    "has_shuttle",
                    models.BooleanField(
                        default=False, help_text="Free shuttle service to terminal"
                    ),
                ),
                (
                    "has_ev_charging",
                    models.BooleanField(
                        default=False, help_text="EV charging stations"
                    ),
                ),
                (
                    "has_car_wash",
                    models.BooleanField(
                        default=False, help_text="Car wash service available"
                    ),
                ),
                (
                    "has_valet",
                    models.BooleanField(
                        default=False, help_text="Valet service available"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parking Zone",
                "verbose_name_plural": "Parking Zones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ParkingSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spot_number", models.CharField(max_length=20)),
                ("is_covered", models.BooleanField(default=False)),
                (
                    "is_accessible",
                    models.BooleanField(
                        default=False, help_text="Disabled accessible spot"
                    ),
                ),
                (
                    "is_ev_charging",
                    models.BooleanField(default=False, help_text="Has EV charging"),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CAR", "Car/Sedan"),
                            ("SUV", "SUV/Crossover"),
                            ("VAN", "Van/Minivan"),
                            ("TRUCK", "Truck/Pickup"),
                            ("MOTORCYCLE", "Motorcycle"),
                            ("ELECTRIC", "Electric Vehicle"),
                        ],
                        default="CAR",
                        max_length=20,
                    ),
                ),
                ("is_occupied", models.BooleanField(default=False)),
                ("is_reserved", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spots",
                        to="parking.parkingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parking Spot",
                "verbose_name_plural": "Parking Spots",
                "ordering": ["zone", "spot_number"],
                "unique_together": {("zone", "spot_number")},
            },
        ),
        migrations.CreateModel(
            name="ParkingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Service duration in minutes (0 if not applicable)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "available_zones",
                    models.ManyToManyField(
                        blank=True,
                        related_name="available_services",
                        to="parking.parkingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parking Service",
                "verbose_name_plural": "Parking Services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ParkingReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_code",
                    models.CharField(
                        default=parking.models.generate_reservation_code,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CAR", "Car/Sedan"),
                            ("SUV", "SUV/Crossover"),
                            ("VAN", "Van/Minivan"),
                            ("TRUCK", "Truck/Pickup"),
                            ("MOTORCYCLE", "Motorcycle"),
                            ("ELECTRIC", "Electric Vehicle"),
                        ],
                        default="CAR",
                        max_length=20,
                    ),
                ),
                ("vehicle_registration", models.CharField(max_length=20)),
                ("vehicle_make", models.CharField(blank=True, max_length=50)),
                ("vehicle_model", models.CharField(blank=True, max_length=50)),
                ("vehicle_color", models.CharField(blank=True, max_length=30)),
                ("check_in_date", models.DateTimeField()),
                ("check_out_date", models.DateTimeField()),
                ("actual_check_in", models.DateTimeField(blank=True, null=True)),
                ("actual_check_out", models.DateTimeField(blank=True, null=True)),
                (
                    "flight_number",
                    models.CharField(
                        blank=True, help_text="Associated flight number", max_length=20
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "service_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("ACTIVE", "Active (Checked In)"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("special_requests", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="parking.parkingspot",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="parking.parkingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parking Reservation",
                "verbose_name_plural": "Parking Reservations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservationService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="parking.parkingreservation",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_services",
                        to="parking.parkingservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation Service",
                "verbose_name_plural": "Reservation Services",
            },
        ),
        migrations.CreateModel(
            name="ParkingPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CAR", "Car/Sedan"),
                            ("SUV", "SUV/Crossover"),
                            ("VAN", "Van/Minivan"),
                            ("TRUCK", "Truck/Pickup"),
                            ("MOTORCYCLE", "Motorcycle"),
                            ("ELECTRIC", "Electric Vehicle"),
                        ],
                        default="CAR",
                        max_length=20,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "weekly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "monthly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "grace_period_minutes",
                    models.PositiveIntegerField(
                        default=15, help_text="Free grace period in minutes"
                    ),
                ),
                (
                    "max_daily_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum charge per day",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "online_booking_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Percentage discount for online booking",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "loyalty_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Percentage discount for loyalty members",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="parking.parkingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parking Pricing",
                "verbose_name_plural": "Parking Pricing",
                "ordering": ["zone", "vehicle_type"],
                "unique_together": {("zone", "vehicle_type")},
            },
        ),
    ]
