# Generated by Django 5.2.11 on 2026-02-04 10:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in Nigerian Naira', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('currency', models.CharField(default='NGN', max_length=3, verbose_name='currency')),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('USSD', 'USSD'), ('QR', 'QR Code'), ('MOBILE_MONEY', 'Mobile Money'), ('PAYSTACK', 'Paystack')], default='PAYSTACK', max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', max_length=20, verbose_name='status')),
                ('paystack_reference', models.CharField(blank=True, help_text='Unique transaction reference from Paystack', max_length=100, null=True, unique=True, verbose_name='Paystack reference')),
                ('paystack_access_code', models.CharField(blank=True, help_text='Access code for Paystack checkout', max_length=100, verbose_name='Paystack access code')),
                ('paystack_authorization_url', models.URLField(blank=True, help_text='URL to redirect user for payment', verbose_name='Paystack authorization URL')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='card last 4 digits')),
                ('card_type', models.CharField(blank=True, help_text='e.g., visa, mastercard', max_length=20, verbose_name='card type')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='bank name')),
                ('channel', models.CharField(blank=True, help_text='e.g., card, bank, ussd', max_length=50, verbose_name='payment channel')),
                ('gateway_response', models.TextField(blank=True, help_text='Response message from payment gateway', verbose_name='gateway response')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='refund amount')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='refunded at')),
                ('refund_reason', models.TextField(blank=True, verbose_name='refund reason')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment data from gateway', verbose_name='metadata')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INITIATED', 'Payment Initiated'), ('WEBHOOK', 'Webhook Received'), ('VERIFIED', 'Payment Verified'), ('COMPLETED', 'Payment Completed'), ('FAILED', 'Payment Failed'), ('REFUND_INITIATED', 'Refund Initiated'), ('REFUND_COMPLETED', 'Refund Completed')], max_length=20, verbose_name='event type')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Raw data from event', verbose_name='data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment')),
            ],
            options={
                'verbose_name': 'payment log',
                'verbose_name_plural': 'payment logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paystack_reference'], name='payments_pa_paystac_25e13d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking'], name='payments_pa_booking_8fd3de_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='payments_pa_user_id_be07d0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
    ]
