# Generated by Django 5.2.11 on 2026-02-04 10:15

import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airlines', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. A valid email address.', max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('role', models.CharField(choices=[('PASSENGER', 'Passenger'), ('AIRLINE_STAFF', 'Airline Staff'), ('AIRPORT_STAFF', 'Airport Staff'), ('ADMIN', 'Administrator')], default='PASSENGER', help_text="User's role in the system", max_length=20, verbose_name='role')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('airline', models.ForeignKey(blank=True, help_text='Airline this staff member belongs to (for airline staff only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='airlines.airline')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('title', models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('DR', 'Dr.'), ('PROF', 'Prof.')], max_length=10, verbose_name='title')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1, verbose_name='gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[core.validators.validate_phone_number], verbose_name='phone number')),
                ('nationality', models.CharField(blank=True, default='Nigerian', max_length=100, verbose_name='nationality')),
                ('passport_number', models.CharField(blank=True, max_length=20, validators=[core.validators.validate_passport_number], verbose_name='passport number')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='passport expiry date')),
                ('passport_country', models.CharField(blank=True, default='Nigeria', max_length=100, verbose_name='passport issuing country')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='address line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='address line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state/province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('country', models.CharField(blank=True, default='Nigeria', max_length=100, verbose_name='country')),
                ('loyalty_number', models.CharField(blank=True, help_text='Frequent flyer loyalty program number', max_length=20, null=True, unique=True, verbose_name='loyalty number')),
                ('loyalty_points', models.PositiveIntegerField(default=0, verbose_name='loyalty points')),
                ('loyalty_tier', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Bronze', max_length=20, verbose_name='loyalty tier')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, verbose_name='emergency contact name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, validators=[core.validators.validate_phone_number], verbose_name='emergency contact phone')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, verbose_name='relationship')),
                ('preferred_seat', models.CharField(choices=[('WINDOW', 'Window'), ('AISLE', 'Aisle'), ('MIDDLE', 'Middle'), ('NO_PREFERENCE', 'No Preference')], default='NO_PREFERENCE', max_length=20, verbose_name='preferred seat')),
                ('meal_preference', models.CharField(choices=[('REGULAR', 'Regular'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('HALAL', 'Halal'), ('KOSHER', 'Kosher'), ('GLUTEN_FREE', 'Gluten Free'), ('NO_PREFERENCE', 'No Preference')], default='NO_PREFERENCE', max_length=50, verbose_name='meal preference')),
                ('special_assistance', models.TextField(blank=True, help_text='Any special assistance or accessibility needs', verbose_name='special assistance requirements')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='profile picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='accounts_cu_role_666d59_idx'),
        ),
    ]
