# Generated by Django 5.2.11 on 2026-02-04 10:15

import core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(help_text='Official name of the airport', max_length=255, verbose_name='airport name')),
                ('code', models.CharField(help_text='3-letter IATA airport code (e.g., ABV, LOS, LHR)', max_length=3, unique=True, validators=[core.validators.validate_airport_code], verbose_name='IATA code')),
                ('icao_code', models.CharField(blank=True, help_text='4-letter ICAO airport code (e.g., DNAA, DNMM, EGLL)', max_length=4, verbose_name='ICAO code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('country', models.CharField(default='Nigeria', max_length=100, verbose_name='country')),
                ('timezone', models.CharField(default='Africa/Lagos', help_text='IANA timezone identifier', max_length=50, verbose_name='timezone')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('is_international', models.BooleanField(default=True, help_text='Whether the airport handles international flights', verbose_name='international')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'airport',
                'verbose_name_plural': 'airports',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='flights_air_code_36cb2c_idx'), models.Index(fields=['city'], name='flights_air_city_5a6128_idx'), models.Index(fields=['country'], name='flights_air_country_0c733b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('terminal', models.CharField(help_text='Terminal identifier (e.g., T1, A, International)', max_length=10, verbose_name='terminal')),
                ('gate_number', models.CharField(help_text='Gate number (e.g., A1, B12)', max_length=10, verbose_name='gate number')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('BOARDING', 'Boarding'), ('MAINTENANCE', 'Under Maintenance'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=20, verbose_name='status')),
                ('is_international', models.BooleanField(default=True, help_text='Whether this gate handles international flights', verbose_name='international gate')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='flights.airport')),
            ],
            options={
                'verbose_name': 'gate',
                'verbose_name_plural': 'gates',
                'ordering': ['airport', 'terminal', 'gate_number'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('flight_number', models.CharField(help_text='Flight number (e.g., W3101, BA75)', max_length=10, validators=[core.validators.validate_flight_number], verbose_name='flight number')),
                ('scheduled_departure', models.DateTimeField(verbose_name='scheduled departure')),
                ('scheduled_arrival', models.DateTimeField(verbose_name='scheduled arrival')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='actual departure')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='actual arrival')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECK_IN_OPEN', 'Check-in Open'), ('BOARDING', 'Boarding'), ('GATE_CLOSED', 'Gate Closed'), ('DEPARTED', 'Departed'), ('IN_FLIGHT', 'In Flight'), ('LANDED', 'Landed'), ('ARRIVED', 'Arrived'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('DIVERTED', 'Diverted')], default='SCHEDULED', max_length=20, verbose_name='status')),
                ('delay_reason', models.TextField(blank=True, help_text='Reason for delay if applicable', verbose_name='delay reason')),
                ('economy_price', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Price in Nigerian Naira', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='economy price')),
                ('business_price', models.DecimalField(decimal_places=2, default=Decimal('150000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='business price')),
                ('first_class_price', models.DecimalField(decimal_places=2, default=Decimal('300000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='first class price')),
                ('available_economy_seats', models.PositiveIntegerField(default=0, verbose_name='available economy seats')),
                ('available_business_seats', models.PositiveIntegerField(default=0, verbose_name='available business seats')),
                ('available_first_class_seats', models.PositiveIntegerField(default=0, verbose_name='available first class seats')),
                ('is_international', models.BooleanField(default=False, verbose_name='international flight')),
                ('meal_service', models.BooleanField(default=True, verbose_name='meal service')),
                ('wifi_available', models.BooleanField(default=False, verbose_name='WiFi available')),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='airlines.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airlines.airline')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='flights.airport', verbose_name='destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='flights.airport', verbose_name='origin')),
                ('arrival_gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_flights', to='flights.gate', verbose_name='arrival gate')),
                ('departure_gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_flights', to='flights.gate', verbose_name='departure gate')),
            ],
            options={
                'verbose_name': 'flight',
                'verbose_name_plural': 'flights',
                'ordering': ['scheduled_departure'],
            },
        ),
        migrations.AddIndex(
            model_name='gate',
            index=models.Index(fields=['airport', 'status'], name='flights_gat_airport_5542f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gate',
            unique_together={('airport', 'terminal', 'gate_number')},
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['flight_number'], name='flights_fli_flight__794da4_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['scheduled_departure'], name='flights_fli_schedul_b040af_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['origin', 'destination'], name='flights_fli_origin__ff1479_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['status'], name='flights_fli_status_e6e528_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['airline', 'scheduled_departure'], name='flights_fli_airline_a44b52_idx'),
        ),
    ]
