# Generated by Django 5.2.11 on 2026-02-04 10:15

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('name', models.CharField(help_text='Official name of the airline', max_length=255, verbose_name='airline name')),
                ('code', models.CharField(help_text='2-letter IATA airline code (e.g., BA, W3, P4)', max_length=2, unique=True, validators=[core.validators.validate_airline_code], verbose_name='IATA code')),
                ('icao_code', models.CharField(blank=True, help_text='3-letter ICAO airline code (e.g., BAW, ARA, APK)', max_length=3, verbose_name='ICAO code')),
                ('country', models.CharField(default='Nigeria', help_text='Country where the airline is based', max_length=100, verbose_name='country')),
                ('headquarters', models.CharField(blank=True, help_text='City where the airline is headquartered', max_length=255, verbose_name='headquarters')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airlines/logos/', verbose_name='logo')),
                ('primary_color', models.CharField(blank=True, help_text='Hex color code (e.g., #FF0000)', max_length=7, verbose_name='primary color')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the airline is currently operating', verbose_name='active')),
                ('alliance', models.CharField(blank=True, choices=[('STAR_ALLIANCE', 'Star Alliance'), ('ONEWORLD', 'oneworld'), ('SKYTEAM', 'SkyTeam'), ('NONE', 'None')], default='NONE', help_text='Airline alliance membership', max_length=50, verbose_name='alliance')),
                ('description', models.TextField(blank=True, help_text='Brief description of the airline', verbose_name='description')),
            ],
            options={
                'verbose_name': 'airline',
                'verbose_name_plural': 'airlines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='airlines_ai_code_9fa522_idx'), models.Index(fields=['is_active'], name='airlines_ai_is_acti_7b78f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('registration', models.CharField(help_text='Aircraft registration (e.g., 5N-ABC for Nigerian)', max_length=10, unique=True, validators=[core.validators.validate_aircraft_registration], verbose_name='registration number')),
                ('aircraft_type', models.CharField(choices=[('B738', 'Boeing 737-800'), ('B38M', 'Boeing 737 MAX 8'), ('B744', 'Boeing 747-400'), ('B77W', 'Boeing 777-300ER'), ('B788', 'Boeing 787-8 Dreamliner'), ('B789', 'Boeing 787-9 Dreamliner'), ('A320', 'Airbus A320'), ('A20N', 'Airbus A320neo'), ('A321', 'Airbus A321'), ('A333', 'Airbus A330-300'), ('A359', 'Airbus A350-900'), ('A388', 'Airbus A380-800'), ('E190', 'Embraer E190'), ('E195', 'Embraer E195'), ('AT72', 'ATR 72'), ('OTHR', 'Other')], default='B738', max_length=4, verbose_name='aircraft type')),
                ('model_name', models.CharField(blank=True, help_text='Specific model name if different from type', max_length=100, verbose_name='model name')),
                ('name', models.CharField(blank=True, help_text='Optional nickname for the aircraft', max_length=100, verbose_name='aircraft name')),
                ('total_seats', models.PositiveIntegerField(default=180, help_text='Total passenger capacity', verbose_name='total seats')),
                ('first_class_seats', models.PositiveIntegerField(default=0, verbose_name='first class seats')),
                ('business_class_seats', models.PositiveIntegerField(default=0, verbose_name='business class seats')),
                ('economy_class_seats', models.PositiveIntegerField(default=180, verbose_name='economy class seats')),
                ('year_manufactured', models.PositiveIntegerField(blank=True, null=True, verbose_name='year manufactured')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='serial number')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='last maintenance date')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='next maintenance date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the aircraft is currently in service', verbose_name='active')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'In Maintenance'), ('GROUNDED', 'Grounded'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('airline', models.ForeignKey(help_text='Airline that owns/operates this aircraft', on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='airlines.airline')),
            ],
            options={
                'verbose_name': 'aircraft',
                'verbose_name_plural': 'aircraft',
                'ordering': ['airline', 'registration'],
                'indexes': [models.Index(fields=['registration'], name='airlines_ai_registr_ccaf87_idx'), models.Index(fields=['airline', 'is_active'], name='airlines_ai_airline_b36434_idx')],
            },
        ),
    ]
