# Generated by Django 5.2.11 on 2026-02-04 10:15

import core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airlines', '0001_initial'),
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='6-character booking reference (e.g., ABC123)', max_length=6, unique=True, validators=[core.validators.validate_booking_reference], verbose_name='booking reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('BOARDED', 'Boarded'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20, verbose_name='status')),
                ('seat_class', models.CharField(choices=[('FIRST', 'First Class'), ('BUSINESS', 'Business Class'), ('ECONOMY', 'Economy Class')], default='ECONOMY', max_length=20, verbose_name='seat class')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='base price')),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='taxes')),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='fees')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='discount')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total price')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='contact phone')),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests or notes', verbose_name='special requests')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='booked at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('DR', 'Dr.'), ('MSTR', 'Master'), ('MISS', 'Miss')], default='MR', max_length=10, verbose_name='title')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('passenger_type', models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child (2-11)'), ('INFANT', 'Infant (0-2)')], default='ADULT', max_length=10, verbose_name='passenger type')),
                ('passport_number', models.CharField(blank=True, max_length=20, validators=[core.validators.validate_passport_number], verbose_name='passport number')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='passport expiry')),
                ('passport_country', models.CharField(default='Nigeria', max_length=100, verbose_name='passport country')),
                ('nationality', models.CharField(default='Nigerian', max_length=100, verbose_name='nationality')),
                ('seat_number', models.CharField(blank=True, max_length=5, validators=[core.validators.validate_seat_number], verbose_name='seat number')),
                ('is_checked_in', models.BooleanField(default=False, verbose_name='checked in')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='checked in at')),
                ('has_boarded', models.BooleanField(default=False, verbose_name='boarded')),
                ('boarded_at', models.DateTimeField(blank=True, null=True, verbose_name='boarded at')),
                ('meal_preference', models.CharField(choices=[('REGULAR', 'Regular'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('HALAL', 'Halal'), ('KOSHER', 'Kosher'), ('GLUTEN_FREE', 'Gluten Free')], default='REGULAR', max_length=50, verbose_name='meal preference')),
                ('special_assistance', models.TextField(blank=True, verbose_name='special assistance')),
                ('checked_baggage', models.PositiveIntegerField(default=23, verbose_name='checked baggage (kg)')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'passenger',
                'verbose_name_plural': 'passengers',
                'ordering': ['booking', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('seat_number', models.CharField(help_text='Seat number (e.g., 12A, 1F)', max_length=5, validators=[core.validators.validate_seat_number], verbose_name='seat number')),
                ('seat_class', models.CharField(choices=[('FIRST', 'First Class'), ('BUSINESS', 'Business Class'), ('ECONOMY', 'Economy Class')], default='ECONOMY', max_length=20, verbose_name='seat class')),
                ('position', models.CharField(choices=[('WINDOW', 'Window'), ('MIDDLE', 'Middle'), ('AISLE', 'Aisle')], max_length=10, verbose_name='position')),
                ('row_number', models.PositiveIntegerField(verbose_name='row number')),
                ('has_extra_legroom', models.BooleanField(default=False, verbose_name='extra legroom')),
                ('is_exit_row', models.BooleanField(default=False, verbose_name='exit row')),
                ('has_power_outlet', models.BooleanField(default=False, verbose_name='power outlet')),
                ('is_blocked', models.BooleanField(default=False, help_text='Seat is blocked and cannot be booked', verbose_name='blocked')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='airlines.aircraft')),
            ],
            options={
                'verbose_name': 'seat',
                'verbose_name_plural': 'seats',
                'ordering': ['aircraft', 'row_number', 'seat_number'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reference'], name='bookings_bo_referen_881a91_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='bookings_bo_user_id_0e7f91_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['flight'], name='bookings_bo_flight__72ac3f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('aircraft', 'seat_number')},
        ),
    ]
