# Generated by Django 5.2.11 on 2026-02-04 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('email_booking', models.BooleanField(default=True, verbose_name='booking emails')),
                ('email_flight_updates', models.BooleanField(default=True, verbose_name='flight update emails')),
                ('email_payment', models.BooleanField(default=True, verbose_name='payment emails')),
                ('email_promotions', models.BooleanField(default=False, verbose_name='promotional emails')),
                ('email_account', models.BooleanField(default=True, verbose_name='account emails')),
                ('sms_booking', models.BooleanField(default=True, verbose_name='booking SMS')),
                ('sms_flight_updates', models.BooleanField(default=True, verbose_name='flight update SMS')),
                ('sms_payment', models.BooleanField(default=False, verbose_name='payment SMS')),
                ('sms_promotions', models.BooleanField(default=False, verbose_name='promotional SMS')),
                ('push_booking', models.BooleanField(default=True, verbose_name='booking push notifications')),
                ('push_flight_updates', models.BooleanField(default=True, verbose_name='flight update push notifications')),
                ('push_payment', models.BooleanField(default=True, verbose_name='payment push notifications')),
                ('push_promotions', models.BooleanField(default=False, verbose_name='promotional push notifications')),
                ('in_app_all', models.BooleanField(default=True, verbose_name='all in-app notifications')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='quiet hours enabled')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start time for quiet hours (no notifications)', null=True, verbose_name='quiet hours start')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End time for quiet hours', null=True, verbose_name='quiet hours end')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('BOOKING_CANCELLATION', 'Booking Cancellation'), ('BOOKING_REMINDER', 'Booking Reminder'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('REFUND_PROCESSED', 'Refund Processed'), ('FLIGHT_DELAY', 'Flight Delay'), ('FLIGHT_CANCELLATION', 'Flight Cancellation'), ('FLIGHT_GATE_CHANGE', 'Gate Change'), ('FLIGHT_BOARDING', 'Boarding Call'), ('FLIGHT_DEPARTURE', 'Flight Departed'), ('FLIGHT_ARRIVAL', 'Flight Arrived'), ('CHECKIN_OPEN', 'Check-in Open'), ('CHECKIN_REMINDER', 'Check-in Reminder'), ('ACCOUNT_WELCOME', 'Welcome'), ('ACCOUNT_PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_EMAIL_VERIFICATION', 'Email Verification'), ('PROMOTION', 'Promotion'), ('LOYALTY_POINTS', 'Loyalty Points Update'), ('SYSTEM_MAINTENANCE', 'System Maintenance'), ('GENERAL', 'General')], default='GENERAL', max_length=30, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('html_message', models.TextField(blank=True, help_text='HTML version of the message for email', verbose_name='HTML message')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App Notification')], default='IN_APP', max_length=10, verbose_name='channel')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10, verbose_name='priority')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('is_sent', models.BooleanField(default=False, verbose_name='sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='delivered')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('related_booking_id', models.UUIDField(blank=True, null=True, verbose_name='related booking')),
                ('related_flight_id', models.IntegerField(blank=True, null=True, verbose_name='related flight')),
                ('related_payment_id', models.UUIDField(blank=True, null=True, verbose_name='related payment')),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate to when notification is clicked', verbose_name='action URL')),
                ('action_text', models.CharField(blank=True, help_text='Text for the action button', max_length=50, verbose_name='action text')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed', verbose_name='error message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx'), models.Index(fields=['channel', 'is_sent'], name='notificatio_channel_747fd1_idx')],
            },
        ),
    ]
